### ISSUE TITLE
k8s repo Network is unreachable

### ISSUE THREAD

**Issue by samyang2558** [tungstenfabric/tf-devstack#6]
I am in China. When installing k8s, the installation source network is unreachable. How can I replace the google installation source? The specific error is as follows: "TASK [k8s : make cache to import gpg keys] *********************************** ************************************************** ************************************************** *************
 [WARNING]: Consider using the yum module rather than running 'yum'. If you need to use command because yum is insufficient you can add 'warn: false' to this command task or set
'command_warnings=False' in ansible.cfg to get rid of this message.

Fatal: [192.168.200.97]: FAILED! => {"changed": true, "cmd": ["yum", "-q", "makecache", "-y", "--disablerepo=*", "--enablerepo=Kubernetes"], "delta": "0:02:30.743957", "end": "2019-11-06 09:12:39.284766", "msg": "non-zero return code", "rc": 1, "start": "2019-11-06 09:10:08.540809", "stderr": "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/ Repodata/repomd.xml:[Errno 14] curl#7 - \"Failed to connect to 2404:6800:4008:802::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud. Google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4008:802::200e: Network is unreachable\" \nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404: 6800:4008:802::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno14] curl#7 - \"Failed to connect to 2404:6800:4008:802::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/ Kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4012::200e: Network is unreachable\"\nTrying other mirror.\nhttps:// Packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4012::200e: Network is unreachable \"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4012::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4012::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos/kubernetes- El7-x86_64/repodata/repomd.xml: [Er Rno 14] curl#7 - \"Failed to connect to 2404:6800:4008:803::200e: Network is unreachable\"\nTrying other mirror.\nhttps://packages.cloud.google.com/yum/repos /kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4008:803::200e: Network is unreachable\"\nTrying other mirror.\n \n\n One of the configured repositories failed (k8s repo),\n and yum doesn't have enough cached to to. At this point the only\n safe thing yum can do isfail. There are a few ways to work \"fix\" this:\n\n 1. Contact the upstream for the repository and get them to fix the problem.\n\n 2. Reconfigure the baseurl/etc. for the repository, to point to a working\n This is most often useful if you are using a newer\n distribution release than is supported by the repository (and the\n packages for the previous distribution release still work).\n\n 3. Run the command with the repository temporarily Disabled\n yum --disa Blerepo=Kubernetes ...\n\n 4. Disable the repository permanently, so yum won't use it by default. Yum\n will then just ignore the repository until you permanently enable it\n again or use --enablerepo for Temporary usage:\n\n yum-config-manager --disable Kubernetes\n or\n subscription-manager repos --disable=Kubernetes\n\n 5. Configure the failing repository to be skipped, if it is unavailable.\ n Note that yum will try to contact the repo. when it runs most commands,\n so will have to try and fail each time (and thus. yum will be be much\n slower). If it is a very temporary problem though , this is often a nice\n compromise:\n\n yum-config-manager --save --setopt=Kubernetes.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from Kubernetes: [Errno 256] No more Mirrors to try.\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to Connect to 2404:6800:4008:802::200e: Network is unreachable\"\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14 ] curl#7 - \"Failed to connect to 2404:6800:4008:802::200e: Network is unreachable\"\nhttps://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/ Repodata/repomd.xml: [Errno 14] curl#7 - \"Failed to connect to 2404:6800:4008:802::200e: Network is unreachable\"\nhttps://packages.cloud.google.com/yum /repos/kubernetes-el7-x86_64/repodata/repomd.x

**Comment by vmbrasseur** [comment]
Hello, @samyang2558!

We don't use GitHub issues for reporting bugs, we use the Tungsten Fabric Jira.

I've transferred this bug report over to there. Please use this link to add further comments and keep track of the work: https://jira.tungsten.io/browse/TFB-1515
